'use client';
import { useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

const base=[{d:'Sep 12',sales:920,cost:590,profit:214},{d:'Sep 13',sales:1180,cost:710,profit:286},{d:'Sep 14',sales:1080,cost:680,profit:254},{d:'Sep 15',sales:1360,cost:805,profit:342},{d:'Sep 16',sales:1490,cost:900,profit:374},{d:'Sep 17',sales:1310,cost:786,profit:326},{d:'Sep 18',sales:1670,cost:980,profit:427}];
export default function AnalyticsPanel(){
 const [range,setRange]=useState('7 Days');
 return <div className="product-frame p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-extrabold">Profit dashboard</div><div className="mt-1 text-xs text-[#847c91]">Demo values for interface preview</div></div><div className="flex gap-1 rounded-lg border border-[#e7e2ee] bg-white p-1">{['Today','7 Days','30 Days','Custom'].map(x=><button key={x} onClick={()=>setRange(x)} className={`rounded-md px-2.5 py-1.5 text-[10px] font-bold ${range===x?'bg-[#211062] text-white':'text-[#71697e]'}`}>{x}</button>)}</div></div><div className="mt-5 grid grid-cols-2 gap-2.5 lg:grid-cols-5">{[['Gross Sales','$9,010'],['Product Cost','$5,451'],['Marketplace Fees','$1,026'],['Net Profit','$2,223'],['Profit Margin','24.7%']].map(([l,v])=><div key={l} className="rounded-xl border border-[#e8e3ef] bg-[#fcfbff] p-3"><div className="text-[10px] font-semibold text-[#81798e]">{l}</div><div className="mt-1 text-lg font-extrabold">{v}</div></div>)}</div><div className="mt-3 grid gap-3 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-[#e8e3ef] p-3"><div className="mb-2 text-[11px] font-bold">Profit over time</div><div className="h-[230px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={base} margin={{left:-18,right:8,top:8}}><defs><linearGradient id="pfit" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#8b3dff" stopOpacity={.25}/><stop offset="95%" stopColor="#8b3dff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#f0edf5" vertical={false}/><XAxis dataKey="d" tick={{fontSize:9,fill:'#8a8296'}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:9,fill:'#8a8296'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,border:'1px solid #e8e3ef',fontSize:10}}/><Area type="monotone" dataKey="profit" stroke="#7a36e3" strokeWidth={2.2} fill="url(#pfit)"/></AreaChart></ResponsiveContainer></div></div><div className="rounded-xl border border-[#e8e3ef] p-3"><div className="mb-2 text-[11px] font-bold">Sales vs cost</div><div className="h-[230px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={base} margin={{left:-18,right:5,top:8}}><CartesianGrid stroke="#f0edf5" vertical={false}/><XAxis dataKey="d" hide/><YAxis tick={{fontSize:9,fill:'#8a8296'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:10,border:'1px solid #e8e3ef',fontSize:10}}/><Bar dataKey="sales" fill="#6d28d9" radius={[4,4,0,0]}/><Bar dataKey="cost" fill="#d7c5ff" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></div></div></div>
}
