import Link from 'next/link';
import { ArrowRight, Check, FileSpreadsheet, LineChart, PackageSearch, RefreshCcw, Tags, Zap } from 'lucide-react';
import Reveal from './Reveal';
import SectionHeading from './SectionHeading';
import DashboardPreview from './DashboardPreview';
import ProfitCalculator from './ProfitCalculator';
import Pricing from './Pricing';
import Faq from './Faq';
import AnalyticsPanel from './AnalyticsPanel';
import { allFeatures } from '@/data/site';
import { ListingPreview, MonitoringPreview, ProductHunterPreview, ReportsPreview, SheetPreview, Workflow } from './ProductVisuals';

function Hero(){return <section className="relative overflow-hidden border-b border-[#efeaf5] bg-[linear-gradient(180deg,#fff_0%,#fcfaff_100%)]"><div className="hero-glow"/><div className="container-site relative grid min-h-[690px] items-center gap-12 py-20 lg:grid-cols-[.9fr_1.1fr]"><Reveal><div className="eyebrow mb-5"><Zap size={14}/>The all-in-one dropshipping automation platform</div><h1 className="max-w-[650px] text-[42px] leading-[1.02] font-[850] tracking-[-.052em] sm:text-[56px] lg:text-[64px]">Automate Your Dropshipping Business From <span className="gradient-text">One Powerful Platform.</span></h1><p className="muted mt-6 max-w-[620px] text-[18px] leading-8">Discover profitable products, publish listings, monitor stock and prices, track orders, calculate profits and keep your Google Sheets updated automatically.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary" href="/signup">Start Free <ArrowRight size={17}/></Link><a className="btn-secondary" href="#dashboard">Watch Product Tour</a></div><div className="mt-6 flex flex-wrap gap-x-5 gap-y-2 text-sm font-semibold text-[#655d73]">{['Fast setup','Built for scaling sellers','All tools in one dashboard'].map(x=><span key={x} className="flex items-center gap-2"><span className="grid h-5 w-5 place-items-center rounded-full bg-[#f0e8ff] text-[#6d28d9]"><Check size={12}/></span>{x}</span>)}</div></Reveal><Reveal delay={.08}><DashboardPreview compact/></Reveal></div></section>}

function IntegrationStrip(){return <section className="section-tight"><div className="container-site"><SectionHeading center eyebrow="Connected workflow" title="Everything connected. Everything automated." text="Start with the confirmed workflow around eBay and Google Sheets. Additional integrations should only be presented once they are finalized."/><div className="mx-auto mt-9 grid max-w-2xl grid-cols-2 gap-4"><div className="card p-5 text-center"><div className="text-3xl font-black tracking-tight"><span className="text-[#e53238]">e</span><span className="text-[#0064d2]">b</span><span className="text-[#f5af02]">a</span><span className="text-[#86b817]">y</span></div><div className="muted mt-2 text-xs">Confirmed marketplace focus</div></div><div className="card p-5 text-center"><div className="flex items-center justify-center gap-2 text-lg font-black text-[#238647]"><FileSpreadsheet/>Google Sheets</div><div className="muted mt-2 text-xs">Orders & profit workflow</div></div></div></div></section>}

function ProductValue(){return <section className="section bg-[#fbfaff]"><div className="container-site"><SectionHeading center eyebrow="One connected system" title="Stop Managing Your Store Across Ten Different Tools." text="AutoDropshipPrime brings product research, listing automation, monitoring, orders and profit analytics into one workflow."/><div className="mt-10"><Workflow/></div></div></section>}

function FeatureSplit({eyebrow,title,text,visual,reverse=false,cta}:{eyebrow:string,title:string,text:string,visual:React.ReactNode,reverse?:boolean,cta:string}){return <section className="section"><div className={`container-site grid items-center gap-12 lg:grid-cols-2 ${reverse?'lg:[&>*:first-child]:order-2':''}`}><Reveal>{visual}</Reveal><Reveal><div className="eyebrow mb-4">{eyebrow}</div><h2 className="text-[36px] leading-[1.08] font-[820] tracking-[-.035em] sm:text-[46px]">{title}</h2><p className="muted mt-5 text-[17px] leading-7">{text}</p><div className="mt-6 space-y-3">{['Clear status and context','Realistic operational UI','Built around one connected workflow'].map(x=><div className="flex items-center gap-2 text-sm font-semibold" key={x}><Check size={16} className="text-[#6d28d9]"/>{x}</div>)}</div><Link href={cta} className="mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-[#6d28d9]">Explore feature <ArrowRight size={15}/></Link></Reveal></div></section>}

function FeatureGrid(){return <section className="section bg-[#fbfaff]"><div className="container-site"><SectionHeading eyebrow="All-in-one" title="Too Much to Manage? Put It All in One Place." text="A connected operating layer for product research, listing, monitoring, orders, finance and reporting."/><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{allFeatures.map((f,i)=><Link href={f.href} key={f.title} className={`card group p-5 transition hover:-translate-y-1 hover:shadow-[0_20px_50px_rgba(48,25,104,.10)] ${i===0||i===5?'lg:col-span-2':''}`}><div className="flex items-center justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f1eaff] text-[#6d28d9]"><f.icon size={19}/></span><ArrowRight size={16} className="text-[#a69cb6] transition group-hover:translate-x-1 group-hover:text-[#6d28d9]"/></div><div className="mt-5 text-base font-extrabold">{f.title}</div><p className="muted mt-2 text-sm leading-6">{f.text}</p>{(i===0||i===5)&&<div className="mt-5 h-12 rounded-lg border border-[#e8e2ef] bg-[linear-gradient(90deg,#f5efff,#fff4fb)]"/>}</Link>)}</div></div></section>}

function HowItWorks(){return <section className="section"><div className="container-site"><SectionHeading center eyebrow="How it works" title="From Product Discovery to Profit Tracking."/><div className="mt-12 grid gap-8 md:grid-cols-4">{['Connect Your Store','Find & List Products','Let Automation Monitor Operations','Track Orders and Profit'].map((x,i)=><div key={x} className="relative"><div className="text-4xl font-black text-[#e1d6f8]">0{i+1}</div><div className="mt-3 text-base font-extrabold">{x}</div><p className="muted mt-2 text-sm leading-6">{['Connect the confirmed marketplace workflow.','Research products and move selections into listing preparation.','Keep stock and price changes visible from one center.','Review orders, calculations, profit and reporting data.'][i]}</p>{i<3&&<div className="absolute left-[72%] top-6 hidden w-[60%] border-t border-dashed border-[#c9b8e8] md:block"/>}</div>)}</div></div></section>}

function Benefits(){return <section className="section-tight border-y border-[#eee9f4] bg-[#211062] text-white"><div className="container-site grid gap-6 md:grid-cols-4">{[['Less manual work','Automate repetitive operational tasks.'],['Better visibility','See orders, pricing and profitability in one place.'],['Faster workflow','Move from product discovery to listing faster.'],['One platform','Reduce tool-switching across daily operations.']].map(([t,d])=><div key={t}><div className="text-xs font-black uppercase tracking-[.12em] text-[#cbb5ff]">{t}</div><div className="mt-3 text-[17px] font-bold leading-7 text-white/90">{d}</div></div>)}</div></section>}

export default function HomePage(){return <>
<Hero/><IntegrationStrip/><ProductValue/>
<FeatureSplit eyebrow="Product research" title="Find Better Products Without Hours of Manual Research." text="Review supplier, source price, estimated selling price, margin, category and stock context from a focused product discovery interface." visual={<ProductHunterPreview/>} cta="/features/product-hunting"/>
<FeatureSplit reverse eyebrow="Auto listing" title="Turn Winning Products Into Listings Faster." text="Move selected products into a structured editor for titles, descriptions, cost, selling price, margin and quantity before publishing." visual={<ListingPreview/>} cta="/features/auto-listing"/>
<section className="section bg-[#f7f4fb]"><div className="container-site"><SectionHeading eyebrow="Stock + price monitoring" title="Prices Change. Stock Changes. Your System Keeps Watching." text="Keep critical supplier changes visible from one monitoring center, with practical status states and margin context."/><div className="mt-9"><MonitoringPreview/></div></div></section>
<section className="section"><div className="container-site"><SectionHeading eyebrow="Google Sheets automation" title="Your Orders and Profit Sheet, Updated Automatically." text="Turn order, cost, fee, profit and status information into a structured spreadsheet workflow that remains easy to review."/><div className="mt-9"><SheetPreview/></div></div></section>
<section className="section bg-[#fbfaff]"><div className="container-site grid items-start gap-10 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Calculation dashboard" title="Know Your Numbers Before You Scale." text="Estimate profit with selling price, product cost, marketplace fees, shipping, taxes and other costs before taking action."/><ProfitCalculator/></div></section>
<section className="section"><div className="container-site"><SectionHeading eyebrow="Profit dashboard" title="Understand Where Your Profit Is Actually Coming From." text="Review gross sales, product cost, marketplace fees, net profit and margin with useful reporting periods."/><div className="mt-9"><AnalyticsPanel/></div></div></section>
<section className="section bg-[#fbfaff]"><div className="container-site"><SectionHeading eyebrow="Reports" title="Turn Store Data Into Decisions." text="Bring sales, profit, orders, product performance, inventory and price-change reporting into one consistent workspace."/><div className="mt-9"><ReportsPreview/></div></div></section>
<FeatureGrid/>
<section id="dashboard" className="section"><div className="container-site"><SectionHeading center eyebrow="Product dashboard" title="A Workspace That Feels Like Real Operating Software." text="The marketing site uses reusable dashboard components so product visuals remain consistent across pages."/><div className="mt-10"><DashboardPreview/></div></div></section>
<HowItWorks/><Benefits/>
<section className="section"><div className="container-site"><SectionHeading center eyebrow="Pricing" title="Simple Plans for Growing Sellers." text="Pricing and plan limits remain configurable placeholders until final commercial details are supplied."/><div className="mt-9"><Pricing/></div></div></section>
<section id="faq" className="section bg-[#fbfaff]"><div className="container-site grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="FAQ" title="Straight Answers About the Workflow." text="The copy avoids claiming integrations or capabilities that have not been confirmed."/><Faq/></div></section>
<section className="section"><div className="container-site"><div className="brand-gradient overflow-hidden rounded-[24px] px-6 py-14 text-center text-white sm:px-12 sm:py-16"><div className="mx-auto max-w-3xl"><div className="text-xs font-black uppercase tracking-[.14em] text-white/65">AutoDropshipPrime</div><h2 className="mt-4 text-[36px] leading-[1.06] font-[850] tracking-[-.04em] sm:text-[50px]">Run Your Dropshipping Operation From One Place.</h2><p className="mx-auto mt-5 max-w-xl text-[17px] leading-7 text-white/75">Spend less time jumping between tools and more time growing your store.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/signup" className="rounded-[10px] bg-white px-5 py-3 font-extrabold text-[#32158c]">Start Free</Link><Link href="/contact" className="rounded-[10px] border border-white/30 bg-white/10 px-5 py-3 font-extrabold text-white">Book a Demo</Link></div></div></div></div></section>
</>}
