'use client';
import { useState } from 'react';
import Link from 'next/link';
import { Check } from 'lucide-react';

const plans=[
  {name:'Starter',desc:'For setting up a focused seller workflow.',price:'$XX',features:['Product Hunting','Auto Listing','Stock Monitoring','Orders Dashboard']},
  {name:'Growth',desc:'For stores that need connected monitoring and analytics.',price:'$XX',featured:true,features:['Everything in Starter','Price Monitoring','Google Sheets Sync','Profit Analytics','Reports']},
  {name:'Pro',desc:'For broader operations and configurable requirements.',price:'Custom',features:['Everything in Growth','Expanded store requirements','Reporting configuration','Support configuration']},
];
export default function Pricing({full=false}:{full?:boolean}){
 const [annual,setAnnual]=useState(false);
 return <div><div className="mb-8 flex justify-center"><div className="inline-flex rounded-xl border border-[#e6e0ef] bg-white p-1 text-sm"><button className={`rounded-lg px-4 py-2 font-bold ${!annual?'bg-[#211062] text-white':''}`} onClick={()=>setAnnual(false)}>Monthly</button><button className={`rounded-lg px-4 py-2 font-bold ${annual?'bg-[#211062] text-white':''}`} onClick={()=>setAnnual(true)}>Annual</button></div></div><div className="grid gap-5 lg:grid-cols-3">{plans.map(p=><div key={p.name} className={`relative rounded-[18px] border p-6 ${p.featured?'border-[#8b3dff] bg-[#fbf9ff] shadow-[0_24px_60px_rgba(77,42,164,.12)]':'border-[#e8e2ef] bg-white'}`}>{p.featured&&<div className="absolute right-5 top-5 rounded-full bg-[#efe7ff] px-3 py-1 text-[10px] font-extrabold uppercase tracking-[.08em] text-[#6d28d9]">Highlighted</div>}<h3 className="text-xl font-extrabold">{p.name}</h3><p className="muted mt-2 min-h-[48px] text-sm leading-6">{p.desc}</p><div className="mt-6 flex items-end gap-1"><span className="text-4xl font-black tracking-[-.04em]">{p.price}</span>{p.price!=='Custom'&&<span className="mb-1 text-sm text-[#7a7287]">/mo</span>}</div><div className="mt-1 text-xs text-[#8a8296]">{p.price==='Custom'?'Contact sales':'Configurable placeholder pricing'}</div><Link href={p.name==='Pro'?'/contact':'/signup'} className={`${p.featured?'btn-primary':'btn-secondary'} mt-6 w-full text-sm`}>{p.name==='Pro'?'Contact Sales':'Start Free'}</Link><div className="mt-6 space-y-3">{p.features.map(f=><div key={f} className="flex items-center gap-2 text-sm"><Check size={16} className="text-[#6d28d9]"/><span>{f}</span></div>)}</div></div>)}</div>{full&&<div className="mt-12 table-shell"><table><thead><tr><th>Capability</th><th>Starter</th><th>Growth</th><th>Pro</th></tr></thead><tbody>{['Stores','Active Listings','Product Hunting','Auto Listing','Stock Monitoring','Price Monitoring','Google Sheets Sync','Orders Dashboard','Calculation Dashboard','Profit Dashboard','Reports','Support'].map((r,i)=><tr key={r}><td className="font-bold">{r}</td><td>{i<5?'Included':'—'}</td><td>{i<11?'Included':'Configured'}</td><td>Configured</td></tr>)}</tbody></table></div>}</div>
}
