import { ArrowDown, Check, FileSpreadsheet, Search, SlidersHorizontal, TrendingUp } from 'lucide-react';

export function ProductHunterPreview(){
  const rows=[['Wireless Charger','Supplier A','$18.40','$39.99','40.9%','In Stock'],['Portable Blender','Supplier B','$22.50','$44.99','34.9%','Low Stock'],['Smart Lamp','Supplier C','$14.20','$31.99','38.2%','In Stock']];
  return <div className="product-frame p-4 sm:p-5"><div className="flex items-center gap-2"><div className="flex flex-1 items-center gap-2 rounded-lg border border-[#e7e2ee] bg-white px-3 py-2 text-xs text-[#8a8295]"><Search size={14}/>Search products</div><button className="grid h-9 w-9 place-items-center rounded-lg border border-[#e7e2ee]"><SlidersHorizontal size={14}/></button></div><div className="mt-4 table-shell"><table><thead><tr>{['Product','Supplier','Source','Sell','Margin','Stock'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td className="font-bold">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td className="font-bold text-[#6d28d9]">{r[4]}</td><td><span className={r[5]==='Low Stock'?'status warn':'status good'}>{r[5]}</span></td></tr>)}</tbody></table></div></div>
}

export function ListingPreview(){
  return <div className="product-frame p-5"><div className="flex items-center justify-between border-b border-[#eeeaf4] pb-4"><div><div className="text-xs font-bold uppercase tracking-[.1em] text-[#81798e]">Listing editor</div><div className="mt-1 text-base font-extrabold">Portable mini blender</div></div><span className="status neutral">Draft</span></div><div className="mt-5 grid gap-4 sm:grid-cols-[140px_1fr]"><div className="grid min-h-[150px] place-items-center rounded-xl bg-gradient-to-br from-[#f1eaff] to-[#fff0fb]"><div className="h-16 w-16 rounded-2xl bg-gradient-to-br from-[#32158c] to-[#f22eb7] shadow-xl"/></div><div className="space-y-3"><label className="block"><span className="mb-1 block text-[10px] font-bold uppercase text-[#81798e]">Title</span><div className="rounded-lg border border-[#e7e2ee] px-3 py-2.5 text-sm font-semibold">Portable USB Rechargeable Blender</div></label><label className="block"><span className="mb-1 block text-[10px] font-bold uppercase text-[#81798e]">Description</span><div className="min-h-[64px] rounded-lg border border-[#e7e2ee] px-3 py-2.5 text-xs leading-5 text-[#6f687b]">Compact personal blender with rechargeable battery and travel cup.</div></label><div className="grid grid-cols-3 gap-2">{[['Cost','$22.50'],['Selling price','$44.99'],['Margin','34.9%']].map(([l,v])=><div key={l} className="rounded-lg border border-[#e7e2ee] p-2"><div className="text-[9px] uppercase text-[#8a8295]">{l}</div><div className="mt-1 text-xs font-extrabold">{v}</div></div>)}</div></div></div><div className="mt-4 flex justify-end gap-2"><button className="btn-secondary min-h-[38px] px-4 text-xs">Save Draft</button><button className="btn-primary min-h-[38px] px-4 text-xs">Create Listing</button></div></div>
}

export function MonitoringPreview(){
 const rows=[['Wireless Headphones','$18.40 → $20.10','$39.99 → $42.99','In Stock','Updated'],['Portable Blender','$22.50','$44.99','Low Stock','Attention'],['Smart Lamp','$14.20','$31.99','Out of Stock','Review']];
 return <div className="product-frame overflow-hidden"><div className="flex items-center justify-between border-b border-[#ebe7f1] bg-white p-4"><div><div className="text-sm font-extrabold">Monitoring center</div><div className="mt-1 text-[11px] text-[#837b8f]">Supplier changes • Demo data</div></div><span className="status good">Active</span></div><div className="table-shell rounded-none border-0"><table><thead><tr>{['Product','Supplier price','Store price','Stock','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td className="font-bold">{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td><td><span className={r[3]==='In Stock'?'status good':r[3]==='Low Stock'?'status warn':'status bad'}>{r[3]}</span></td><td>{r[4]}</td></tr>)}</tbody></table></div></div>
}

export function SheetPreview(){
 const rows=[['Sep 18','#ADP-1284','Wireless Charger','$39.99','$18.40','$5.20','$16.39','40.9%','Completed'],['Sep 18','#ADP-1283','Portable Blender','$44.99','$22.50','$6.79','$15.70','34.9%','Processing'],['Sep 17','#ADP-1282','Smart Lamp','$31.99','$14.20','$5.58','$12.21','38.2%','Completed']];
 return <div className="grid gap-5 lg:grid-cols-[1.7fr_.8fr]"><div className="product-frame overflow-hidden"><div className="flex items-center justify-between border-b border-[#e5eee6] bg-[#f4fbf5] px-4 py-3"><div className="flex items-center gap-2 text-sm font-extrabold"><FileSpreadsheet size={17} className="text-[#218a49]"/> Orders & Profit Sheet</div><span className="status good">Synced</span></div><div className="table-shell rounded-none border-0"><table><thead><tr>{['Date','Order','Product','Sale','Cost','Fees','Profit','Margin','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r[1]}>{r.map((c,i)=><td key={i} className={i===6?'font-extrabold text-[#137b66]':''}>{c}</td>)}</tr>)}</tbody></table></div><div className="border-t border-[#e8e3ef] bg-[#fbfffb] px-4 py-3 text-[11px] font-semibold text-[#4e7e5e]">New order row added • UI demo animation target</div></div><div className="card flex flex-col justify-center p-5"><div className="text-xs font-extrabold uppercase tracking-[.12em] text-[#7d748a]">Connected flow</div>{['New Order','AutoDropshipPrime','Calculate Cost + Profit','Google Sheet Updated'].map((s,i)=><div key={s}><div className={`mt-3 rounded-xl border p-3 text-sm font-bold ${i===1?'border-[#cbb6f5] bg-[#f6f1ff] text-[#5f25c3]':'border-[#e8e3ef]'}`}>{s}</div>{i<3&&<div className="grid h-6 place-items-center text-[#8d7baa]"><ArrowDown size={14}/></div>}</div>)}</div></div>
}

export function Workflow(){
 return <div className="grid gap-3 md:grid-cols-6">{['Find','List','Monitor','Sell','Track','Analyze'].map((x,i)=><div key={x} className="relative"><div className="card flex min-h-[100px] flex-col justify-between p-4"><span className="text-[10px] font-black text-[#8c82a0]">0{i+1}</span><span className="text-sm font-extrabold">{x}</span></div>{i<5&&<div className="absolute -right-3 top-1/2 z-10 hidden w-6 border-t border-dashed border-[#b8a7da] md:block"/>}</div>)}</div>
}

export function ReportsPreview(){return <div className="product-frame p-5"><div className="flex items-center justify-between"><div><div className="text-sm font-extrabold">Reports</div><div className="mt-1 text-xs text-[#80788d]">Choose a dataset and reporting period</div></div><div className="flex gap-2"><button className="btn-secondary min-h-[36px] px-3 text-[11px]">CSV</button><button className="btn-secondary min-h-[36px] px-3 text-[11px]">Spreadsheet</button><button className="btn-secondary min-h-[36px] px-3 text-[11px]">PDF</button></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{['Sales Report','Profit Report','Orders Report','Product Performance','Inventory Report','Price Change Report'].map((x,i)=><div key={x} className="rounded-xl border border-[#e8e3ef] p-4"><div className="flex items-center justify-between"><div className="grid h-9 w-9 place-items-center rounded-lg bg-[#f2ecff] text-[#6d28d9]"><TrendingUp size={16}/></div><Check size={15} className="text-[#a395bb]"/></div><div className="mt-4 text-sm font-extrabold">{x}</div><div className="mt-1 text-[11px] leading-5 text-[#81798e]">Configured report UI • Enable exports supported by the production backend.</div></div>)}</div></div>}
