'use client';
import { useMemo, useState } from 'react';

const Field = ({ label, value, onChange }: { label:string; value:number; onChange:(n:number)=>void }) => <label className="block"><span className="mb-1.5 block text-[11px] font-bold uppercase tracking-[.06em] text-[#7c7488]">{label}</span><div className="flex items-center rounded-lg border border-[#e5e0ed] bg-white px-3"><span className="text-xs text-[#9a93a5]">$</span><input value={value} onChange={e=>onChange(Number(e.target.value)||0)} type="number" className="w-full bg-transparent px-2 py-2.5 text-sm font-bold outline-none"/></div></label>;

export default function ProfitCalculator(){
  const [sell,setSell]=useState(49.99),[cost,setCost]=useState(21.4),[fees,setFees]=useState(6.75),[ship,setShip]=useState(3.2),[tax,setTax]=useState(1.1),[other,setOther]=useState(0.8);
  const result=useMemo(()=>{const total=cost+fees+ship+tax+other; const profit=sell-total; return {profit,margin:sell?profit/sell*100:0,roi:cost?profit/cost*100:0,breakEven:total}},[sell,cost,fees,ship,tax,other]);
  return <div className="product-frame grid gap-0 overflow-hidden lg:grid-cols-[1.15fr_.85fr]">
    <div className="p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><div className="text-sm font-extrabold">Profit calculator</div><div className="muted mt-1 text-xs">Interactive demo values</div></div><span className="status neutral">Demo</span></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Selling Price" value={sell} onChange={setSell}/><Field label="Product Cost" value={cost} onChange={setCost}/><Field label="Marketplace Fees" value={fees} onChange={setFees}/><Field label="Shipping" value={ship} onChange={setShip}/><Field label="Taxes" value={tax} onChange={setTax}/><Field label="Other Costs" value={other} onChange={setOther}/></div></div>
    <div className="brand-gradient p-5 text-white sm:p-7"><div className="text-xs font-bold uppercase tracking-[.12em] text-white/65">Estimate</div><div className="mt-8 grid grid-cols-2 gap-3"><div className="col-span-2 rounded-xl border border-white/15 bg-white/10 p-4"><div className="text-xs text-white/65">Net Profit</div><div className="mt-1 text-3xl font-black">${result.profit.toFixed(2)}</div></div>{[['Profit Margin',`${result.margin.toFixed(1)}%`],['ROI',`${result.roi.toFixed(1)}%`],['Break-even',`$${result.breakEven.toFixed(2)}`]].map(([l,v],i)=><div key={l} className={`${i===2?'col-span-2':''} rounded-xl border border-white/15 bg-white/10 p-4`}><div className="text-[11px] text-white/65">{l}</div><div className="mt-1 text-lg font-extrabold">{v}</div></div>)}</div><p className="mt-6 text-xs leading-5 text-white/65">This calculator is interface demo data. Production calculations should use your final marketplace fee and tax rules.</p></div>
  </div>
}
